### ISSUE TITLE
Toolchain listener Jackson classnotfound error in combination with the Orangebeard listener

### ISSUE THREAD

**Issue by maartenjanvangool** [praegus/toolchain-fixtures#19]
## Summary
See below. We get a dependency conflict on Jackson. 

## Steps to reproduce
Using the latest toolchain listerner (1.2.0-BETA-5) in combination with the latest toolchain fixtures (1.26). 

## Relevant logs and/or screenshots
```2021-09-03 14:28:46.434 test Failed 'null' message='failed' details='java.lang.Exception: Not all tests executed. Completed 0 of 32 tests.
    at fitnesse.junit.JUnitRunNotifierResultsListener.close(JUnitRunNotifierResultsListener.java:108)
    at util.FileUtil.close(FileUtil.java:170)
    at fitnesse.testrunner.CompositeFormatter.close(CompositeFormatter.java:29)
    at util.FileUtil.close(FileUtil.java:170)
    at fitnesse.testrunner.MultipleTestsRunner.allTestingComplete(MultipleTestsRunner.java:87)
    at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:72)
    at fitnesse.junit.FitNesseRunner.executeTests(FitNesseRunner.java:580)
    at fitnesse.junit.FitNesseRunner.runPages(FitNesseRunner.java:497)
    at nl.hsac.fitnesse.junit.HsacFitNesseRunner.runPages(HsacFitNesseRunner.java:216)
    at fitnesse.junit.FitNesseRunner.run(FitNesseRunner.java:478)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
    at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
    at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
## Possible fixes

The toolchain fixtures use an older version of Azure dependencies. Which uses an older version of Jackson.

**Comment by joroelev** [comment]
Did run into this issue.  Workaround is to exclude the Azure dependencies like so (if using Maven): 
`<dependency>
    <groupId>nl.praegus</groupId>
    <artifactId>toolchain-fixtures</artifactId>
    <version>${toolchain.fixtures.version}</version>
    <exclusions>
        <exclusion>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
        </exclusion>
    </exclusions>
</dependency>`
